# Generated by Django 5.2.5 on 2025-09-19 20:03

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='username')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], verbose_name='gender')),
                ('national_code', models.CharField(max_length=10, verbose_name='national code')),
                ('birthday_date', django_jalali.db.models.jDateField(verbose_name='birthday date')),
                ('ceremony_datetime', django_jalali.db.models.jDateTimeField(verbose_name='ceremony datetime')),
                ('country', models.CharField(default='Iran', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
